services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"          
      - "--providers.docker=true"     
      - "--entrypoints.web.address=:80"
      - "--accesslog=true"          
    ports:
      - "80:80"
      - "8080:8080"                  
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  pikachu:
    image: hashicorp/http-echo
    command: ["-text=Pikachu API"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pikachu.rule=Host(`pikachu.localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.pikachu.middlewares=strip-api@docker"
      - "traefik.http.services.pikachu.loadbalancer.server.port=5678"

  charizard:
    image: hashicorp/http-echo
    command: ["-text=Charizard API"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.charizard.rule=Host(`charizard.localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.charizard.middlewares=strip-api@docker"
      - "traefik.http.services.charizard.loadbalancer.server.port=5678"

  bulbasaur:
    image: hashicorp/http-echo
    command: ["-text=Bulbasaur API"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bulbasaur.rule=Host(`bulbasaur.localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.bulbasaur.middlewares=strip-api@docker"
      - "traefik.http.services.bulbasaur.loadbalancer.server.port=5678"

 
  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: "neo4j/test"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.neo4j.rule=Host(`neo4j.localhost`) && PathPrefix(`/browser`)"
      - "traefik.http.routers.neo4j.entrypoints=web"
      - "traefik.http.routers.neo4j.middlewares=neo4j-auth@docker"
      - "traefik.http.services.neo4j.loadbalancer.server.port=7474"
    ports:
      - "7474"
      - "7687:7687"


  strip-api:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.strip-api.stripprefix.prefixes=/api"

  
  neo4j-auth:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.neo4j-auth.basicauth.users=neo4j:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"  

  nginx-welcome:
    image: nginx:latest 
    ports:
      - "80" 
    volumes:
      - ./index.html:/usr/share/nginx/html 
    depends_on:
      - mi-app
  
